# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='slides/')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='slides',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.Slide'),
        ),
    ]
