# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
