# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0002_show_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='num',
        ),
        migrations.RemoveField(
            model_name='show',
            name='slides',
        ),
        migrations.AddField(
            model_name='slide',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slide',
            name='show',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='slides.Show'),
        ),
    ]
